# Generated by Django 5.0.7 on 2024-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='negative_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='positive_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
